struct CharactersModel {
    var characters: [CharacterModel]
    var total: Int?
    
    // Receives the struct generated by the characters list service parser
    init(charactersEntity: [CharacterEntity], total: Int?) {
        self.total = total
        
        let characters = charactersEntity.compactMap {
            CharacterModel(character: $0)
        }
        
        self.characters = characters
    }
}
